FROM tryton/tryton:7.6-office
ENV DB_HOSTNAME=
ENV DB_USER=
ENV DB_PASSWORD=
ENV DATABASE_NAME=
ENV TRYTOND_CONFIG=/etc/trytond.conf
ENV TRYTOND_DATABASE_URI=postgresql://DB_USER:DB_PASSWORD@DB_HOSTNAME:5432/?dbname=DATABASE_NAME
ENV TRYTOND_ATTACHMENT_FILESTORE=True
ENV TRYTOND_DATABASE_LANGUAGE=DE
ENV TRYTOND_WEB_HOSTNAME=

USER root

RUN apt-get update && \
    apt-get install nano -y && \
    pip3 install --break-system-packages --no-cache-dir gf-account-de-skr04
    

COPY init-modules.sh /

USER trytond